Issue65 validate all examples
RalphTro/epcis-event-hash-generator pull request #66
Opened 2022-03-29 15:19 UTC by RalphTro

Hi @Echsecutor , 
ALL XML events and all but one JSON/JSON-LD files (--> came across two things to be discussed with José/Mark - so this effort was also valuable for the standardisation work) are now conformant to the respective schemas (still WIP though). Just in case you would like to go on...
I will adjust the file in question (epcisDocWithXMLstartTagAndErrorDeclaration.jsonld) as soon as the schema is finalised. 
Kind regards,
@RalphTro

2022-04-12 15:07 UTC, Echsecutor requested changes
I did not comment on every place where a gs1 context is added abut not needed, those actually don't matter. But there is one place where we do need the example context, otherwise we can not parse the jsonld file

2022-04-12 15:07 UTC, Echsecutor commented on tests/examples/ReferenceEventHashAlgorithm3.jsonld
> -  "@context": ["https://gs1.github.io/EPCIS/epcis-context.jsonld",{"example": "https://ns.example.com/epcis"}],
example namespace/context is needed below

2022-04-12 15:07 UTC, Echsecutor commented on tests/examples/epcisDocWithDefaultSchemaInContext.jsonld
> +      "example": "http://ns.example.com/epcis/"
example context probably does not hurt here, but is not needed?

2022-04-12 15:07 UTC, Echsecutor commented on tests/examples/epcisDocWithSingleEvent.jsonld
> +      "gs1": "https://gs1.org/voc/"
probably we need neither example nor gs1 context in this example, but does not hurt to keep it

2022-04-14 07:51 UTC, RalphTro commented
Hi @Echsecutor, 
Made quite a number of adjustments of namespace declarations (I am not 100% sure if esp. the json files are already correct - the current version of the JSON schema does not seem to take ns declarations into consideration yet (alerted José to this) and especially replaced inline declarations with header-based one. Additional/superflous ns decalarations can IMHO be disregarded, so we can leave them in.

2022-06-20 08:09 UTC, Echsecutor commented
fixes https://github.com/RalphTro/epcis-event-hash-generator/issues/37

2022-12-16 09:03 UTC, Echsecutor approved these changes

2022-12-16 09:03 UTC, merged